### ISSUE TITLE
Questions on the ScanNet dataset

### ISSUE THREAD

**Issue by JNZZZ** [mellody11/PCAM-With-RandLA-Net#2]
Thank you for your great work!
Cause the ScanNet dataset's TEST SET not contains labels, we have to convert the checkpoint got from the VAL SET to the format that the online ScanNet Website required. Do you have the 'convert code' in your project?

**Comment by liuxuexun** [comment]
Our project do not contrain the 'convert code', may be you can check on their offical [website](https://kaldir.vc.in.tum.de/scannet_benchmark/).
